chore: UI upt sync search with alpha branch
bitcashorg/masterbots pull request #223
Opened 2024-05-21 22:15 UTC by AndlerRL

# Changelog:

- This is a cherry-pick of each work done by @TopETH that have to go to the search branch. These are:
  - https://github.com/bitcashorg/masterbots/pull/209
  - https://github.com/bitcashorg/masterbots/pull/212
  - https://github.com/bitcashorg/masterbots/pull/213
  - https://github.com/bitcashorg/masterbots/pull/214

## TODO:

- Work on check if PR https://github.com/bitcashorg/masterbots/pull/205, https://github.com/bitcashorg/masterbots/pull/206, https://github.com/bitcashorg/masterbots/pull/208 are not in the `search` branch. 
- Cherry pick PR https://github.com/bitcashorg/masterbots/pull/216

2024-05-21 22:21 UTC, gaboesquivel requested changes

2024-05-21 22:21 UTC, gaboesquivel commented on apps/masterbots.ai/components/shared/category-tabs/category-tabs.tsx
> +'use client'
@AndlerRL dont use client for this. use aria-data css.

2024-05-21 22:21 UTC, gaboesquivel commented on apps/masterbots.ai/components/shared/thread-list-accordion.tsx
> +'use client'
dont use client here, remember we need to discuss as team everytime we want to `use client`

2024-05-21 22:21 UTC, gaboesquivel commented on apps/masterbots.ai/components/shared/thread-list-reload.tsx
> +// ! This component is not necessary to be split this way, only functionality.
This is work in progress, you can ignore it

2024-05-21 22:21 UTC, gaboesquivel commented on apps/masterbots.ai/components/shared/thread-list.tsx
> +  const { isFetchingNextPage, fetchNextPage, data, refetch } = useInfiniteQuery(
we dont want use client. that's why we are doing infinite scrolling the nextjs way

2024-05-21 22:22 UTC, gaboesquivel commented
Pretty much all changes are not needed, all we need to add to `search` once its completed is css updates.

2024-05-21 22:29 UTC, AndlerRL commented on apps/masterbots.ai/components/shared/thread-list-accordion.tsx
> +'use client'
Is there any reason to not use `use client`? Why to put all the weight to the server side? :thinking:

2024-05-21 22:33 UTC, AndlerRL commented on apps/masterbots.ai/components/shared/category-tabs/category-tabs.tsx
> +'use client'
Why aria on the CSS? The idea here is to scroll into the thread location, not to change the styling. How do I use then client functions without a client component? The `scrollIntoView` is client side. Why not to `use client` here? :thinking:

2024-05-21 22:56 UTC, gaboesquivel commented on apps/masterbots.ai/components/shared/thread-list-accordion.tsx
> +'use client'
- we are following next14 app router standards to benefits from nextjs features, that's the point.  
- you need to `use client` as long resort when any other way to do it with as server component.   
- all state needs to be handled thru url and aria data first as in `<ThreadHeading>` we use `data-[state=open]:bg-mirage` instead of `const[open,setOpen] = useState()`.
- when you `use client` on layout component can possibly get out of sync with  nextjs app router state and therefore not update the rendered data.  
- best practice is `use client` only in small components like buttons and forms, but not on layout components cos you loose a lot of the benefits of using nextjs, basically you turn the whole app into a  regular react app without next. you need follow the nextjs standard way.
- when you start using `use client` you not only go against the technical design but also starting to create web vitals issues

2024-10-03 20:57 UTC, AndlerRL commented
As mentioned at [this comment](https://github.com/bitcashorg/masterbots/pull/221#issuecomment-2392307728), these updates are not longer required:

@TopETH was requested to check the missing fixes that are here to develop AND prior that to the `search` branch however, this was not successful and, during this time (while PR remained in draft), the product design has change hence, the UI fixes (and most of the component re-usability improvements) that were required before are already on develop (not from this branches). Now this version collides with develop and the logic behind will no longer go anymore and we will be using the ICL with our main DB to connect and do the data vectoring. Closing.

2024-10-03 20:57 UTC, closed without merging