fix: UI/UX feedbacks 2
bitcashorg/masterbots pull request #24
Opened 2024-02-27 04:35 UTC by TopETH

## Change Logs

- Fixed padding and space issues
- Removed bold style
- Removed redirection to single thread view for threads list on browser view on the Chevron icon.
- Added Profile card hero banner at User thread list.
- Increased the thread maximum width to 1024px at Bot/User thread list.
- For new chats the input suggestion was updated:  `Start New Chat with ${botName}`.
- For continuing chats (thread accordion open) the input suggestion was updated:  `Continue This Chat with ${botName}`

## DEMO

![image](https://github.com/bitcashorg/masterbots/assets/79193919/e851c7d1-b925-46d3-83f7-77f0f7a59e87)
![image](https://github.com/bitcashorg/masterbots/assets/79193919/e7383745-db82-4a44-843a-c62c43108d18)
![image](https://github.com/bitcashorg/masterbots/assets/79193919/bb2e78b4-252b-4f79-a0ad-d1fe006f9e9a)

2024-02-27 16:21 UTC, AndlerRL requested changes
There are some improvements to do on the changes! I left some feedbacks, please take care of them.

2024-02-27 16:21 UTC, AndlerRL commented on apps/masterbots.ai/components/chat-list.tsx
> +            className={`border-none ${isThread ? 'relative' : ''}`}
Please put className `transition-all ease-in-out duration-200` for all cards and components with hover/focus classNames that are not based on the accordion component. I suggest adding a default border with transparent color for all thread cards, so that way, you only set the border colour instead of setting all the borders. This is to avoid content shifting.

2024-02-27 16:21 UTC, AndlerRL commented on apps/masterbots.ai/components/chat-list.tsx
> +            triggerClass={`dark:border-mirage border-gray-300 hover:rounded-xl !rounded-b-[0] border-b
The rounded value should be 8px for all thread cards

2024-02-27 16:21 UTC, AndlerRL commented on apps/masterbots.ai/components/chat-list.tsx
> +            ${isThread ? 'sticky top-0 md:-top-10 z-[1] dark:bg-[#18181b] bg-[#f4f4f5] border-l-[0] px-3 [&[data-state=open]]:!bg-gray-300 dark:[&[data-state=open]]:!bg-mirage [&[data-state=open]]:ro
As comment from above, the border-radius should be 8px for thread cards.

2024-02-27 16:21 UTC, AndlerRL commented on apps/masterbots.ai/components/chat.tsx
> +    if (activeThread?.threadId) {
I'm not sure what is this redirection for. Does this mean that if we have an active thread it will take us to the focused view?

On a new feature, if a user decides to continue a thread (or start a new one) by hitting the `enter` key or submit button on the chat input field, it should open a new pop-up with the new/current selected thread to continue with the whole conversation and upon refresh, it takes you to this route, like Instagram (visual + UX + functionality) and X  (UX + functionality) for example.

2024-02-27 16:21 UTC, AndlerRL commented on apps/masterbots.ai/components/thread-list.tsx
>          className="border-none relative"
As commented on the `chat-list` component, Add the default classNames to this thread card and the border-radius changes.

I highly recommend you make the same component for both lists, there are small changes to consider them different at this point. Unique aspects can be conditional props, so it is easier for you the change, and improve maintenance.

2024-02-27 16:21 UTC, AndlerRL commented on apps/masterbots.ai/lib/hooks/use-thread.tsx
> +      router.push(
I see that you can add this on page reload instead of here. We want instead open the pop-up here with the thread conversation. Please follow the feedback given on the related change to this.

Redirection is fine, but it is not the action to trigger the redirection.

2024-02-27 16:54 UTC, TopETH commented on apps/masterbots.ai/components/chat.tsx
> +    if (activeThread?.threadId) {
Oh, Then I can implement it on the next ticket.
This is for redirection to the single thread view when the user hit the enter key or submit button on the chat input field.

2024-02-27 16:55 UTC, AndlerRL commented on apps/masterbots.ai/components/chat.tsx
> +    if (activeThread?.threadId) {
Ok, yes let's do that. For now, you can comment on the code block.

2024-02-28 02:46 UTC, AndlerRL approved these changes
LGTM! Thanks for taking care the observations. Merging! 👍

2024-02-28 02:47 UTC, merged